When running on production you want to use a real database instead of using H2. Let's explain how to use Postgres.

After installing Docker, execute the following command to run a postgresql container:

[source,bash]
----
docker run -it \
    -p 5432:5432 \
    -e POSTGRES_USER=dbuser \
    -e POSTGRES_PASSWORD=theSecretPassword \
    -e POSTGRES_DB=micronaut \
    postgres:10.5-alpine
----

Add Postgresql driver dependency to `build.gradle`:

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=postgresql,indent=0]
----

Add application specific configuration for production. Create the file `application-postgresql.yml`
as follows:

[source,yml]
.src/main/resources/application-postgresql.yml
----
include::{sourceDir}/src/main/resources/application-postgresql.yml[tag=datasourcePostgresql]
----

There are different options to use this new configuration file and activate the `postgresql` environment:


[source,bash]
----
$ MICRONAUT_ENVIRONMENTS=postgresql ./gradlew run
----

Or while running the application jar file:

[source,bash]
----
$ java -Dmicronaut.environments=postgresql -jar myapp.jar
----

In both cases the output will be as follows and we can see that `postgresql` environment is active:

[source,bash]
----
12:52:57.812 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [postgresql]
12:52:58.594 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
...
----


WARNING: The problem with this approach is that the **production credentials** are included in both the application jar
 file and in the repository.

To fix this problem, delete the file `application-postgresql.yml` and use the externalized configuration defined previously.

There are different ways to set those properties:

- Environment variables:

[source,bash]
----
$ export JDBC_URL=jdbc:postgresql://localhost:5432/micronaut
$ export JDBC_USER=dbuser
$ export JDBC_PASSWORD=theSecretPassword
$ export JDBC_DRIVER=org.postgresql.Driver

$ java -jar myapp.jar
----

- Configuration file. Create a configuration file for production in the same directory as the jar run the application with:

[source,bash]
----
$ java -Dmicronaut.config.files=production-config-file.yml \
       -jar myapp.jar
----

For more information please take a look at Micronaut's documentation about
https://docs.micronaut.io/snapshot/guide/index.html#config[Application Configuration].
