include::{commondir}/common-validation.adoc[indent=0]

Create two classes to encapsulate Save and Update operations:

[source,java]
.src/main/java/example/micronaut/GenreSaveCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/GenreSaveCommand.java[]
----
<1> Annotate the class with `@Introspected` to generate the Bean Metainformation at compile time.

[source,java]
.src/main/java/example/micronaut/GenreUpdateCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/GenreUpdateCommand.java[]
----
<1> Use `javax.validation.constraints` Constraints to ensure the incoming data matches your expectations.

Create `GenreController`, a controller which exposes a resource with the common CRUD operations:

[source,java]
.src/main/java/example/micronaut/GenreController.java
----
include::{sourceDir}/src/main/java/example/micronaut/GenreController.java[]
----

<1> It is critical that any blocking I/O operations (such as fetching the data from the database) are offloaded to a separate thread pool that does not block the Event loop.
<2> The class is defined as a controller with the `@Controller` annotation mapped to the path `/genres`.
<3> Constructor injection.
<4> Maps a `GET` request to `/genres/{id}` which attempts to show a genre. This illustrates the use of a URL path variable.
<5> Returning `null` when the genre doesn't exist makes Micronaut to response with 404 (not found).
<6> Maps a `PUT` request to `/genres` which attempts to update a genre.
<7> Add `@Valid` to any method parameter which requires validation. Use a POJO supplied as a JSON payload in the request to populate command.
<8> It is easy to add custom headers to the response.
<9> Maps a `GET` request to `/genres` which returns a list of genres. This mapping illustrates URL parameters being mapped to a single POJO.
<10> Maps a `POST` request to `/genres` which attempts to save a genre.
<11> Maps a `POST` request to `/ex` which generates an exception.
<12> Maps a `DELETE` request to `/genres/{id}` which attempts to remove a genre. This illustrates the use of a URL path variable.

