include::{commondir}/common-validation.adoc[]

Create two classes to encapsulate Save and Update operations:

[source,java]
.src/main/java/example/micronaut/genre/GenreSaveCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreSaveCommand.java[]
----

[source,java]
.src/main/java/example/micronaut/genre/GenreUpdateCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreUpdateCommand.java[]
----

Create several POJOs to encapsulate Sorting and Pagination:


[source,java]
.src/main/java/example/micronaut/SortingOrder.java
----
include::{sourceDir}/src/main/java/example/micronaut/SortingOrder.java[]
----

[source,java]
.src/main/java/example/micronaut/SortingArguments.java
----
include::{sourceDir}/src/main/java/example/micronaut/SortingArguments.java[]
----

[source,java]
.src/main/java/example/micronaut/PaginationArguments.java
----
include::{sourceDir}/src/main/java/example/micronaut/PaginationArguments.java[]
----

Create a `ConfigurationProperties` object to encapsulate the configuration of the default `max` value.

[source,java]
.src/main/java/example/micronaut/ApplicationConfiguration.java
----
include::{sourceDir}/src/main/java/example/micronaut/ApplicationConfiguration.java[]
----

[source,java]
.src/main/java/example/micronaut/ApplicationConfigurationProperties.java
----
include::{sourceDir}/src/main/java/example/micronaut/ApplicationConfigurationProperties.java[]
----

Create `GenreController`, a controller which exposes a resource with the common CRUD operations:

[source,java]
.src/main/java/example/micronaut/genre/GenreController.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreController.java[]
----

<1> Add `@Validated` annotation at the class level to any class that requires validation.
<2> The class is defined as a controller with the `@Controller` annotation mapped to the path `/genres`.
<3> Constructor injection.
<4> Maps a `GET` request to `/genres/{id}` which attempts to show a genre. This illustrates the use of a URL path variable.
<5> Returning `null` when the genre doesn't exist makes Micronaut to response with 404 (not found).
<6> Maps a `PUT` request to `/genres` which attempts to update a genre.
<7> Add `@Valid` to any method parameter which requires validation. Use a POJO supplied as a JSON payload in the request to populate command.
<8> It is easy to add custom headers to the response.
<9> Maps a `GET` request to `/genres` which returns a list of genres. This mapping illustrates optional URL parameters.
<10> Maps a `POST` request to `/genres` which attempts to save a genre.
<11> Maps a `DELETE` request to `/genres/{id}` which attempts to remove a genre. This illustrates the use of a URL path variable.

