Micronaut’s validation is built on with the standard framework – JSR 380, also known as Bean Validation 2.0.

Hibernate Validator is a reference implementation of the validation API.

Add the next snippet to `build.gradle`

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=validation,indent=0]
----

Create two classes to encapsulate Save and Update operations:

[source,java]
.src/main/java/example/micronaut/genre/GenreSaveCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreSaveCommand.java[]
----

[source,java]
.src/main/java/example/micronaut/genre/GenreUpdateCommand.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreUpdateCommand.java[]
----

Create `GenreController`, a controller which exposes a resource with the common CRUD operations:

[source,java]
.src/main/java/example/micronaut/genre/GenreController.java
----
include::{sourceDir}/src/main/java/example/micronaut/genre/GenreController.java[]
----

<1> Add `@Validated` annotation at the class level to any class that requires validation.
<2> The class is defined as a controller with the `@Controller` annotation mapped to the path `/genres`.
<3> Constructor injection.
<4> Maps a `GET` request to `/genres/{id}` which attempts to show a genre. This illustrates the use of a URL path variable. If the entity is not found 404 is returned.
<5> Maps a `PUT` request to `/genres` which attempts to update a genre.
<6> Add `@Valid` to any method parameter which requires validation. Use a POGO supplied as a JSON payload in the request to populate command.
<7> It is easy to add custom headers to the response.
<8> Maps a `GET` request to `/genres` which returns a list of genres
<9> Maps a `POST` request to `/genres` which attempts to save a genre.
<10> Maps a `DELETE` request to `/genres/{id}` which attempts to remove a genre. This illustrates the use of a URL path variable.
