=== Data Source configuration

Add the next snippet to `build.gradle` to include the necessary dependencies:

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=jpa,indent=0]
----

<1> Configures Hibernate/JPA EntityManagerFactory beans.
<2> Configures SQL DataSource instances using Hikari Connection Pool.
<3> Add dependency to in-memory H2 Database.

Define the data source in `src/main/resources/application.yml`.

[source,yml]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=datasource]
----

NOTE: This way of defining the datasource properties means that we can externalize the configuration, for example for
production environment, and also provide a default value for development. If the environment variables are not defined
Micronaut will use the default values. +
Also keep in mind that it is necessary to escape the `:` in the connection url using back ticks ```.

=== JPA configuration

Add the next snippet to `src/main/resources/application.yml` to configure JPA:

[source,yml]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=jpa]
----

<1> Entities are scanned in the package `example.micronaut.domain`.
