Create a Junit test which verifies the CRUD operations:

[source,java]
.src/test/java/example/micronaut/GenreControllerTest.java
----
include::{sourceDir}/src/test/java/example/micronaut/genre/GenreControllerTest.java[]
----

<1> To run the application from a unit test you can use the http://docs.micronaut.io/latest/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface.
<2> Register a `HttpClient` bean in the application context and point it to the embedded server URL. The EmbeddedServer interface provides the URL of the server under test which runs on a random port.
<3> As the test's package is not the same as the entities (`example.micronaut.genre` vs `example.micronaut.domain`) it is necessary to specify the packages to scan for entities.
<4> Creating HTTP Requests is easy thanks to Micronaut's fluid API.
<5> If you care just about the object in the response use `retrieve`.
<6> Sometimes, receiving just the object is not enough and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method.

include::{commondir}/common-testApp.adoc[]
